import type { Metadata } from "next";
import { Encode_Sans_Semi_Expanded } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./_components/Nav/Nav";

const encodeSansSemiExpanded = Encode_Sans_Semi_Expanded({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-encode-sans-semi-expanded",
})

const geistSans = Geist({
  variable: "--font-sans-serif",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-sans-serif-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={encodeSansSemiExpanded.variable}>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-between items-center border-b p-4 gap-4 h-16">
            <Nav />
            <div>
              <SignedOut>
                <SignInButton />
                <SignUpButton>
                  <button className="bg-[#6c47ff] text-ceramic-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
